# Generated by Django 2.2.7 on 2019-12-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20191217_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='book_title',
            field=models.IntegerField(),
        ),
    ]
