# Generated by Django 2.2.7 on 2019-12-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20191219_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page',
            new_name='page_number',
        ),
    ]
