# Generated by Django 2.2.7 on 2019-12-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20191220_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
