# Generated by Django 2.2.7 on 2020-01-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200102_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_content',
            name='page_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Page'),
        ),
    ]
